README.md, examples/example-prj/jest.config.mjs, examples/example-prj/jest/setupAfterEnv.ts, packages/prisma-fabbrica/package.json, packages/prisma-fabbrica/scripts/jest-prisma.js, packages/prisma-fabbrica/src/scripts/jest-prisma/setup.ts
=> feat: Provide setupFilesAfterEnv script for jest-prisma

.prettierignore, CONTRIBUTING.md, examples/example-prj/package.json, examples/example-prj/src/__generated__/fabbrica.ts, package-lock.json, package.json, packages/prisma-fabbrica/src/clientHolder.ts, packages/prisma-fabbrica/src/generator.ts, packages/prisma-fabbrica/src/index.ts, packages/prisma-fabbrica/src/setup.ts, packages/prisma-fabbrica/src/templates/index.test.ts, packages/prisma-fabbrica/src/templates/index.ts, packages/ts-compile-testing/.gitignore, packages/ts-compile-testing/fixtures/simple-model/__generated__/fabbrica.ts, packages/ts-compile-testing/fixtures/simple-model/schema.prisma, packages/ts-compile-testing/package.json, packages/ts-compile-testing/scripts/generateFixtures.ts, packages/ts-compile-testing/tsconfig.json
=> test: Compilation fixtures

examples/example-prj/src/__generated__/fabbrica.ts, packages/prisma-fabbrica/src/templates/index.test.ts, packages/prisma-fabbrica/src/templates/index.ts, packages/ts-compile-testing/fixtures/enum-model/__generated__/fabbrica.ts, packages/ts-compile-testing/fixtures/enum-model/schema.prisma, packages/ts-compile-testing/fixtures/simple-model/__generated__/fabbrica.ts
=> feat: Auto generate enum value

README.md, examples/example-prj/src/__generated__/fabbrica/index.js, examples/example-prj/src/sample.test.ts, packages/prisma-fabbrica/src/helpers/createJSONLiteral.ts, packages/prisma-fabbrica/src/helpers/index.ts, packages/prisma-fabbrica/src/helpers/selectors.ts, packages/prisma-fabbrica/src/relations/index.ts, packages/prisma-fabbrica/src/relations/screen.test.ts, packages/prisma-fabbrica/src/relations/screen.ts, packages/prisma-fabbrica/src/templates/__snapshots__/getSourceFile.test.ts.snap, packages/prisma-fabbrica/src/templates/index.ts, packages/ts-compile-testing/fixtures/field-variation/__generated__/fabbrica/index.ts, packages/ts-compile-testing/fixtures/relations-many-to-many/__generated__/fabbrica/index.ts, packages/ts-compile-testing/fixtures/relations-one-to-many/__generated__/fabbrica/index.ts, packages/ts-compile-testing/fixtures/relations-one-to-one/__generated__/fabbrica/index.ts, packages/ts-compile-testing/fixtures/simple-model/__generated__/fabbrica/index.ts
=> Screen built input before create execution

CONTRIBUTING.md
CONTRIBUTING.mdの手順に従い、動作確認をしようとしたところ
```sh
The table `main.User` does not exist in the current database.
```
テーブルが存在していないため、test通過できない状態だったため
CONTRIBUTING.mdに、migrate:testの実行手順を追記しました。
```sh
Test Suites: 3 passed, 3 total
Tests:       9 passed, 9 total
Snapshots:   0 total
Time:        1.494 s, estimated 2 s
```
実行後はtest通過することを確認できています。
認識齟齬、問題などないかレビューお願いいたします。
=> CONTRIBUTING.md add migrate:test

packages/prisma-fabbrica/src/templates/getIdFieldNames.test.ts, packages/prisma-fabbrica/src/templates/index.ts, packages/ts-compile-testing/fixtures/field-variation/__generated__/fabbrica/index.ts, packages/ts-compile-testing/fixtures/field-variation/schema.prisma
=> fix: Models without @id nor @@id

packages/prisma-fabbrica/src/templates/getIdFieldNames.test.ts, packages/prisma-fabbrica/src/templates/index.ts, packages/ts-compile-testing/fixtures/field-variation/__generated__/fabbrica/index.ts, packages/ts-compile-testing/fixtures/field-variation/schema.prisma
=> fix: Extract unique fields when @@unique

packages/prisma-fabbrica/src/templates/autoGenerateModelScalarsOrEnumsFieldArgs.test.ts, packages/prisma-fabbrica/src/templates/index.ts
=> fix: Complex unique fields auto scalar generate

package-lock.json, packages/prisma-fabbrica/package.json, packages/ts-compile-testing/scripts/generateFixtures.ts
=> fix `Node TypeLiteral did not pass test 'isEntityName'` assertion error .

examples/example-prj/src/__generated__/fabbrica/index.d.ts, examples/example-prj/src/__generated__/fabbrica/index.js, packages/prisma-fabbrica/index.mjs, packages/prisma-fabbrica/internal.mjs, packages/prisma-fabbrica/package.json, packages/prisma-fabbrica/scripts/jest-prisma.mjs, packages/prisma-fabbrica/src/internal.ts, packages/prisma-fabbrica/src/scalar/gen.ts, packages/prisma-fabbrica/src/templates/__snapshots__/getSourceFile.test.ts.snap, packages/prisma-fabbrica/src/templates/index.ts, packages/ts-compile-testing/fixtures/field-variation/__generated__/fabbrica/index.ts, packages/ts-compile-testing/fixtures/relations-many-to-many/__generated__/fabbrica/index.ts, packages/ts-compile-testing/fixtures/relations-one-to-many/__generated__/fabbrica/index.ts, packages/ts-compile-testing/fixtures/relations-one-to-one/__generated__/fabbrica/index.ts, packages/ts-compile-testing/fixtures/simple-model/__generated__/fabbrica/index.ts
=> feat: Configure exports map

README.md, examples/example-prj/src/__generated__/fabbrica/index.d.ts, examples/example-prj/src/__generated__/fabbrica/index.js, examples/example-prj/src/customScalarField.test.ts, packages/prisma-fabbrica/src/initialize.ts, packages/prisma-fabbrica/src/internal.ts, packages/prisma-fabbrica/src/scalar/customize.ts, packages/prisma-fabbrica/src/scalar/gen.ts, packages/prisma-fabbrica/src/scalar/types.ts, packages/prisma-fabbrica/src/templates/__snapshots__/getSourceFile.test.ts.snap, packages/prisma-fabbrica/src/templates/autoGenerateModelScalarsOrEnumsFieldArgs.test.ts, packages/prisma-fabbrica/src/templates/index.ts, packages/ts-compile-testing/fixtures/field-variation/__generated__/fabbrica/index.ts, packages/ts-compile-testing/fixtures/relations-many-to-many/__generated__/fabbrica/index.ts, packages/ts-compile-testing/fixtures/relations-one-to-many/__generated__/fabbrica/index.ts, packages/ts-compile-testing/fixtures/relations-one-to-one/__generated__/fabbrica/index.ts, packages/ts-compile-testing/fixtures/simple-model/__generated__/fabbrica/index.ts
=> feat: Allow to custom scalar generation rule

packages/prisma-fabbrica/src/templates/index.ts, packages/ts-compile-testing/fixtures/field-variation/__generated__/fabbrica/index.ts, packages/ts-compile-testing/fixtures/field-variation/schema.prisma
=> fix: Import optional enum type

examples/example-prj/src/__generated__/fabbrica/index.d.ts, examples/example-prj/src/sample.test.ts, packages/prisma-fabbrica/src/templates/__snapshots__/getSourceFile.test.ts.snap, packages/prisma-fabbrica/src/templates/index.ts
=> fix: Export ModelFactoryInterface

README.md, examples/example-prj/src/__generated__/fabbrica/index.d.ts, examples/example-prj/src/__generated__/fabbrica/index.js, examples/example-prj/src/trait.test.ts, packages/prisma-fabbrica/src/templates/__snapshots__/getSourceFile.test.ts.snap, packages/prisma-fabbrica/src/templates/index.ts, packages/ts-compile-testing/fixtures/field-variation/__generated__/fabbrica/index.ts, packages/ts-compile-testing/fixtures/relations-many-to-many/__generated__/fabbrica/index.ts, packages/ts-compile-testing/fixtures/relations-one-to-many/__generated__/fabbrica/index.ts, packages/ts-compile-testing/fixtures/relations-one-to-one/__generated__/fabbrica/index.ts, packages/ts-compile-testing/fixtures/simple-model/__generated__/fabbrica/index.ts
=> feat: Implement traits

README.md, package-lock.json, package.json, packages/prisma-fabbrica/package.json, packages/prisma-fabbrica/src/generator.ts, packages/prisma-fabbrica/src/templates/index.ts, packages/ts-compile-testing/fixtures/field-variation/__generated__/fabbrica/index.ts, packages/ts-compile-testing/package.json
=> Upgrade prisma client v5

packages/prisma-fabbrica/src/generator.ts, packages/prisma-fabbrica/src/getClientModuleSpecifier.test.ts, packages/prisma-fabbrica/src/getClientModuleSpecifier.ts
=> fix: prismaClientModuleSpecifier for win32

examples/example-prj/src/__generated__/fabbrica/index.d.ts, examples/example-prj/src/__generated__/fabbrica/index.js, packages/artifact-testing/.gitignore, packages/artifact-testing/fixtures/field-variation/__generated__/fabbrica/index.ts, packages/artifact-testing/fixtures/relations-many-to-many/__generated__/fabbrica/index.ts, packages/artifact-testing/fixtures/relations-one-to-many/__generated__/fabbrica/index.ts, packages/artifact-testing/fixtures/relations-one-to-one/__generated__/fabbrica/index.ts, packages/artifact-testing/fixtures/simple-model/__generated__/fabbrica/index.ts, packages/artifact-testing/package.json, packages/artifact-testing/tsconfig.json, packages/prisma-fabbrica/package.json, packages/prisma-fabbrica/src/templates/__snapshots__/getSourceFile.test.ts.snap, packages/prisma-fabbrica/src/templates/index.ts
It fixes #281 via reverting #250 .
=> fix: TypeScript error caused by internal symbol

package-lock.json, package.json, packages/prisma-fabbrica/src/helpers/list.ts, packages/prisma-fabbrica/src/templates/ast-tools/createJSONLiteral.ts, packages/prisma-fabbrica/src/templates/index.ts
Upgrade prettier and pretty-quick
=> upgrade prettier

examples/example-prj/src/__generated__/fabbrica/index.d.ts, packages/artifact-testing/fixtures/field-variation/__generated__/fabbrica/index.ts, packages/artifact-testing/fixtures/relations-many-to-many/__generated__/fabbrica/index.ts, packages/artifact-testing/fixtures/relations-one-to-many/__generated__/fabbrica/index.ts, packages/artifact-testing/fixtures/relations-one-to-one/__generated__/fabbrica/index.ts, packages/artifact-testing/fixtures/simple-model/__generated__/fabbrica/index.ts, packages/prisma-fabbrica/src/templates/__snapshots__/getSourceFile.test.ts.snap, packages/prisma-fabbrica/src/templates/index.ts
=> chore: Use explicit import type statement

packages/artifact-testing/.gitignore, packages/artifact-testing/package.json, packages/artifact-testing/tsconfig.esnext.json, packages/artifact-testing/tsconfig.node.json, packages/prisma-fabbrica/src/internal.ts
=> test: Compile with multiple --module options

examples/example-prj/src/__generated__/fabbrica/index.js, packages/artifact-testing/.gitignore, packages/artifact-testing/fixtures/relations-one-to-many/__generated__/fabbrica/index.ts, packages/artifact-testing/fixtures/relations-one-to-one/__generated__/fabbrica/index.ts, packages/artifact-testing/package.json, packages/artifact-testing/tsconfig.esnext.json, packages/artifact-testing/tsconfig.json, packages/artifact-testing/tsconfig.noNullChecks.json, packages/prisma-fabbrica/src/templates/index.ts
=> Sometimes `{}` is not assignable to  ModelFactoryInput

examples/example-prj/src/__generated__/fabbrica/index.js, packages/artifact-testing/fixtures/field-variation/__generated__/fabbrica/index.ts, packages/artifact-testing/fixtures/relations-many-to-many/__generated__/fabbrica/index.ts, packages/artifact-testing/fixtures/relations-one-to-many/__generated__/fabbrica/index.ts, packages/artifact-testing/fixtures/relations-one-to-one/__generated__/fabbrica/index.ts, packages/artifact-testing/fixtures/simple-model/__generated__/fabbrica/index.ts, packages/artifact-testing/tsconfig.json, packages/prisma-fabbrica/src/templates/__snapshots__/getSourceFile.test.ts.snap, packages/prisma-fabbrica/src/templates/index.ts
=> fix: Check indexing access
